const $=s=>document.querySelector(s),input=$("#input");
const sample={specVersion:"1.0",host:{displayName:"Acme Dev Tools",identifier:"did:web:acme.com",documentationUrl:"https://acme.com/docs"},entries:[{identifier:"urn:air:acme.com:server:weather",displayName:"Acme Weather MCP Server",type:"application/mcp-server-card+json",url:"https://api.acme.com/.well-known/server-card.json",description:"Live weather observations and forecasts for requested locations.",capabilities:["CurrentWeather","Forecast"],tags:["weather","forecast"],representativeQueries:["What is the current wind speed in Chicago?","Get the five-day forecast for Seattle."],version:"1.0.0",updatedAt:"2026-07-29T00:00:00Z"}]};
function issue(a,type,title,detail){a.push({type,title,detail})}function url(v,https=false){try{const u=new URL(v);return !https||u.protocol==="https:"}catch{return false}}function domainFromUrn(v){const m=String(v).match(/^urn:air:([^:]+):(?:[^:]+:)+[^:]+$/);return m?.[1]}
function validate(){const raw=input.value.trim(),out=[];let d;if(!raw){render([{type:"error",title:"No catalog provided",detail:"Paste ai-catalog.json content first."}]);return}try{d=JSON.parse(raw)}catch(e){render([{type:"error",title:"Invalid JSON",detail:e.message}]);return}
 if(d.specVersion!=="1.0")issue(out,"error","specVersion must be 1.0","The current AI Catalog manifest examples use specVersion 1.0.");else issue(out,"pass","Catalog version declared","specVersion is 1.0.");
 if(!d.host||typeof d.host.displayName!=="string"||!d.host.displayName.trim())issue(out,"error","Host display name is required","Add host.displayName for the catalog operator.");
 if(d.host?.identifier&&!(/^(did:web:|https?:\/\/|[a-z0-9.-]+\.[a-z]{2,})/i.test(d.host.identifier)))issue(out,"warning","Review host identifier","Use a DID or verifiable domain.");
 if(d.host?.documentationUrl&&!url(d.host.documentationUrl,true))issue(out,"error","Host documentation URL must use HTTPS","Provide a valid public HTTPS URL.");
 if(!Array.isArray(d.entries)||!d.entries.length){issue(out,"error","Catalog has no entries","Add at least one agentic resource.");render(out);return}
 const ids=new Set();d.entries.forEach((e,i)=>{const p=`Entry ${i+1}`;if(!e.identifier)issue(out,"error",`${p}: missing identifier`,"Use urn:air:<publisher>:<namespace>:<name>.");else{const pub=domainFromUrn(e.identifier);if(!pub)issue(out,"error",`${p}: invalid ARD identifier`,"Use a domain-anchored urn:air identifier with namespace and resource name.");else issue(out,"pass",`${p}: identifier is domain anchored`,e.identifier);if(ids.has(e.identifier))issue(out,"error",`${p}: duplicate identifier`,"Every catalog entry must have a unique identifier.");ids.add(e.identifier)}
 if(!e.displayName||typeof e.displayName!=="string")issue(out,"error",`${p}: displayName is required`,"Add a concise human-readable name.");
 if(!e.type||!/^[a-z]+\/[a-z0-9.+-]+$/i.test(e.type))issue(out,"error",`${p}: invalid media type`,"type must be an IANA-style media type such as application/mcp-server-card+json.");
 const hasUrl=Object.prototype.hasOwnProperty.call(e,"url"),hasData=Object.prototype.hasOwnProperty.call(e,"data");if(hasUrl===hasData)issue(out,"error",`${p}: choose exactly one of url or data`,"ARD requires strict value-or-reference exclusivity.");else if(hasUrl&&!url(e.url,true))issue(out,"error",`${p}: artifact URL must use HTTPS`,"Use an absolute HTTPS reference.");else issue(out,"pass",`${p}: artifact delivery is unambiguous`,hasUrl?"Remote URL reference":"Inline data object");
 if(!e.description||e.description.trim().length<20)issue(out,"warning",`${p}: strengthen the description`,"Explain what the resource does and when it should be selected.");
 if(!Array.isArray(e.representativeQueries)||e.representativeQueries.length<2||e.representativeQueries.length>5)issue(out,"warning",`${p}: provide 2–5 representative queries`,"Natural-language examples improve semantic discovery ranking.");else if(e.representativeQueries.some(q=>typeof q!=="string"||q.trim().split(/\s+/).length<4))issue(out,"warning",`${p}: queries are too short`,"Use realistic user requests, not isolated keywords.");else issue(out,"pass",`${p}: representative queries are useful`,`${e.representativeQueries.length} discovery examples supplied.`);
 if(e.updatedAt&&Number.isNaN(Date.parse(e.updatedAt)))issue(out,"error",`${p}: updatedAt is not ISO 8601`,"Use a parseable timestamp such as 2026-07-29T00:00:00Z.");
 if(e.trustManifest){if(!e.trustManifest.identity||!e.trustManifest.identityType)issue(out,"warning",`${p}: incomplete trust manifest`,"Trust metadata should declare identity and identityType.");if(e.trustManifest.attestations&&!Array.isArray(e.trustManifest.attestations))issue(out,"error",`${p}: attestations must be an array`,"Provide an array of typed attestation objects.")}
 });
 const secret=/\b(sk-[A-Za-z0-9_-]{12,}|gh[pousr]_[A-Za-z0-9]{20,}|Bearer\s+[A-Za-z0-9._-]{12,})\b/;if(secret.test(raw))issue(out,"error","Possible secret embedded","Public discovery manifests must not contain live credentials.");if(!out.some(x=>x.type==="error"))issue(out,"pass","Ready for endpoint checks","Host this catalog at /.well-known/ai-catalog.json, then verify JSON content type and CORS.");render(out)}
function render(list){const errors=list.filter(x=>x.type==="error").length,warns=list.filter(x=>x.type==="warning").length,passes=list.filter(x=>x.type==="pass").length,n=Math.max(0,100-errors*18-warns*6),state=errors?"bad":warns?"warn":"good";$("#score").textContent=n;$("#score").className=`score ${state}`;$("#summary").className=`summary ${state}`;$("#summary").innerHTML=`<b>${errors?`${errors} blocking issue${errors>1?"s":""}`:warns?`Valid with ${warns} recommendation${warns>1?"s":""}`:"Catalog preflight passed"}</b><p>${passes} passed · ${warns} warnings · ${errors} errors</p>`;$("#issues").innerHTML=list.map(x=>`<div class="issue ${x.type}"><b>${esc(x.title)}</b><p>${esc(x.detail)}</p></div>`).join("")}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
$("#sample").onclick=()=>{input.value=JSON.stringify(sample,null,2);validate()};$("#clear").onclick=()=>{input.value="";$("#issues").innerHTML="";$("#score").textContent="—"};$("#validate").onclick=validate;document.addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key==="Enter"){e.preventDefault();validate()}});
$("#form").addEventListener("submit",e=>{e.preventDefault();const domain=$("#domain").value.trim().replace(/^https?:\/\//,"").replace(/\/.*$/,"").toLowerCase(),qs=$("#queries").value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),o={specVersion:"1.0",host:{displayName:$("#host").value.trim(),identifier:`did:web:${domain}`},entries:[{identifier:`urn:air:${domain}:${$("#namespace").value.trim().toLowerCase().replace(/[^a-z0-9.-]+/g,"-")}:${$("#slug").value.trim().toLowerCase().replace(/[^a-z0-9.-]+/g,"-")}`,displayName:$("#name").value.trim(),type:$("#type").value,url:$("#url").value.trim(),description:$("#description").value.trim(),representativeQueries:qs}]};input.value=JSON.stringify(o,null,2);validate();location.hash="validator"});input.value=JSON.stringify(sample,null,2);
